version: '3.11'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - minio
    environment:
      - MINIO_ENDPOINT=http://minio:9000
    volumes:
      - ./models:/app/models
    # Wait for MinIO to be ready
    command: >
      sh -c "
        until curl -f http://minio:9000/minio/health/ready; do
          echo 'Waiting for MinIO...'
          sleep 2
        done
        uvicorn appmain:app --host 0.0.0.0 --port 8000
      "

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  minio_data:
