data_source:
    # type can be 'local' for local tests, 's3' for deployment
    type: "s3"
    local_path: "data/dataset.xlsx"
    s3_path: "s3://test-bucket/dataset.xlsx"
    s3_address: "http://minio:9000"
    s3_id: "minioadmin"
    s3_key: "minioadmin"
missing_data:
    # strategy can be 'ignore', 'fill', 'impute', 'synthesize'
    missing_data_strategy: "synthesize"
    # fill value in case of 'fill'    
    fill_value: 0
    # name of model for data synthesis
    model_name: "model_synthesize"
feature_selection:
    # toggle variance check
    variance_check: 1
    variance_threshold: 0.05
    # toggle correlation check
    correlation_check: 1
    correlation_threshold: 0.8
reduction:
    # select approach for dimensionality reduction
    approach: pca
    # set cummulative variance threshold for pca
    pca_variance_threshold: 0.25
    # name of encoder model for dimensionality reduction
    model_name: "model_reduce"
clustering:
    # set minimum cluster size
    min_cluster_size: 40
