data_source:
    # type can be 'local', 'url', 's3'
    type: "local"
    # should be full path to file for given source
    path: "data/dataset.xlsx"
    # path: "s3://test-bucket/dataset.xlsx"
    # for s3, additional info is necessary
    s3_address: "http://127.0.0.1:9000"
    s3_id: "minioadmin"
    s3_key: "minioadmin"
missing_data:
    # strategy can be 'ignore', 'fill', 'impute', 'synthesize'
    missing_data_strategy: "synthesize"
    # fill value in case of 'fill'    
    fill_value: 0
    # name of model for data synthesis
    model_name: "model_synthesize"
feature_selection:
    # toggle variance check
    variance_check: 1
    variance_threshold: 0.05
    # toggle correlation check
    correlation_check: 1
    correlation_threshold: 0.8
reduction:
    # set cummulative variance threshold for pca
    pca_variance_threshold: 0.25
clustering:
    # set minimum cluster size
    min_cluster_size: 40
